
- hosts: web-server1 
  become: true 
  name: example2-1 
  tasks: 
    - name: stop httpd  
      ansible.builtin.service: 
        name: httpd  
        state: stopped 
 
- hosts: web-server2 
  become: true 
  tasks: 
    - name: stop nginx 
      ansible.builtin.service: 
        name: nginx 
        state: stopped 
